[2025-01-25T20:37:34.752+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T20:37:34.767+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_gazettes_data.download_s3_index_version manual__2025-01-25T20:13:16.586213+00:00 [queued]>
[2025-01-25T20:37:34.775+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_gazettes_data.download_s3_index_version manual__2025-01-25T20:13:16.586213+00:00 [queued]>
[2025-01-25T20:37:34.775+0000] {taskinstance.py:2865} INFO - Starting attempt 15 of 16
[2025-01-25T20:37:34.787+0000] {taskinstance.py:2888} INFO - Executing <Task(DownloadContentFromS3): download_s3_index_version> on 2025-01-25 20:13:16.586213+00:00
[2025-01-25T20:37:34.799+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=25720) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-25T20:37:34.800+0000] {standard_task_runner.py:72} INFO - Started process 25752 to run task
[2025-01-25T20:37:34.801+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_gazettes_data', 'download_s3_index_version', 'manual__2025-01-25T20:13:16.586213+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmp_0y2b0k5']
[2025-01-25T20:37:34.803+0000] {standard_task_runner.py:105} INFO - Job 160: Subtask download_s3_index_version
[2025-01-25T20:37:34.848+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_gazettes_data.download_s3_index_version manual__2025-01-25T20:13:16.586213+00:00 [running]> on host 41bcec3d818b
[2025-01-25T20:37:34.918+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_gazettes_data' AIRFLOW_CTX_TASK_ID='download_s3_index_version' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T20:13:16.586213+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-25T20:13:16.586213+00:00'
[2025-01-25T20:37:34.920+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T20:37:34.944+0000] {base.py:84} INFO - Retrieving connection 'minio_s3_conn_id'
[2025-01-25T20:37:34.945+0000] {connection_wrapper.py:391} INFO - AWS Connection (conn_id='minio_s3_conn_id', conn_type='aws') credentials retrieved from extra.
[2025-01-25T20:37:34.945+0000] {warnings.py:112} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2025-01-25T20:37:35.156+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket diario-oficial-db-dump with path vector_db/index.faiss
[2025-01-25T20:37:35.355+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/download_content_from_s3_bucket.py", line 66, in execute
    self.download_from_s3()
  File "/opt/airflow/dags/utils/download_content_from_s3_bucket.py", line 55, in download_from_s3
    shutil.move(os.path.join(filename,local_file_path, key))
TypeError: move() missing 1 required positional argument: 'dst'
[2025-01-25T20:37:35.369+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pull_gazettes_data, task_id=download_s3_index_version, run_id=manual__2025-01-25T20:13:16.586213+00:00, execution_date=20250125T201316, start_date=20250125T203734, end_date=20250125T203735
[2025-01-25T20:37:35.382+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T20:37:35.383+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 160 for task download_s3_index_version (move() missing 1 required positional argument: 'dst'; 25752)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/download_content_from_s3_bucket.py", line 66, in execute
    self.download_from_s3()
  File "/opt/airflow/dags/utils/download_content_from_s3_bucket.py", line 55, in download_from_s3
    shutil.move(os.path.join(filename,local_file_path, key))
TypeError: move() missing 1 required positional argument: 'dst'
[2025-01-25T20:37:35.417+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T20:37:35.440+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T20:37:35.442+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
