[2025-01-28T23:33:23.320+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T23:33:23.338+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_gazettes_data.preprocess_documents_task scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-01-28T23:33:23.351+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_gazettes_data.preprocess_documents_task scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-01-28T23:33:23.352+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-01-28T23:33:23.371+0000] {taskinstance.py:2888} INFO - Executing <Task(PreprocessDocuments): preprocess_documents_task> on 2025-01-27 00:00:00+00:00
[2025-01-28T23:33:23.382+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2510) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T23:33:23.385+0000] {standard_task_runner.py:72} INFO - Started process 2512 to run task
[2025-01-28T23:33:23.384+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_gazettes_data', 'preprocess_documents_task', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmp84m9s793']
[2025-01-28T23:33:23.388+0000] {standard_task_runner.py:105} INFO - Job 251: Subtask preprocess_documents_task
[2025-01-28T23:33:23.440+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_gazettes_data.preprocess_documents_task scheduled__2025-01-27T00:00:00+00:00 [running]> on host 41bcec3d818b
[2025-01-28T23:33:23.525+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_gazettes_data' AIRFLOW_CTX_TASK_ID='preprocess_documents_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-01-28T23:33:23.527+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T23:33:23.541+0000] {logging_mixin.py:190} INFO - Checking pre processed documents log
[2025-01-28T23:33:23.542+0000] {logging_mixin.py:190} INFO - /usr/local/***/data/ingestion_checkpoint_logs/preprocessed_documents_log.csv True
[2025-01-28T23:33:23.550+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/preprocess_documents_simplified.py", line 93, in execute
    self.process_files()
  File "/opt/airflow/dags/utils/preprocess_documents_simplified.py", line 76, in process_files
    preprocessed_document = self.preprocess_file(file)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/preprocess_documents_simplified.py", line 53, in preprocess_file
    with pymupdf.open(source) as pdf_document:
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymupdf/__init__.py", line 2955, in __init__
    raise FileNotFoundError(msg)
pymupdf.FileNotFoundError: no such file: '3106200_2024-11-26_7140.pdf'
[2025-01-28T23:33:23.572+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pull_gazettes_data, task_id=preprocess_documents_task, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250128T233323, end_date=20250128T233323
[2025-01-28T23:33:23.590+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T23:33:23.591+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 251 for task preprocess_documents_task (no such file: '3106200_2024-11-26_7140.pdf'; 2512)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/preprocess_documents_simplified.py", line 93, in execute
    self.process_files()
  File "/opt/airflow/dags/utils/preprocess_documents_simplified.py", line 76, in process_files
    preprocessed_document = self.preprocess_file(file)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/preprocess_documents_simplified.py", line 53, in preprocess_file
    with pymupdf.open(source) as pdf_document:
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymupdf/__init__.py", line 2955, in __init__
    raise FileNotFoundError(msg)
pymupdf.FileNotFoundError: no such file: '3106200_2024-11-26_7140.pdf'
[2025-01-28T23:33:23.641+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-28T23:33:23.665+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T23:33:23.667+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
